
server:
  port: 10001

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp



spring:
  application:
    name: cloud-web
    
           
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
     preferIpAddress: true
    
    

ribbon:
  eureka:
    enabled: true