server:
  port: 20015

spring:
  application:
    name: cloud-unified-service-core
  datasource:
    url: jdbc:mysql://localhost:3306/saascloud?autoReconnect=true&amp;characterEncoding=UTF-8&amp;useUnicode=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
            naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
              
    properties:
            hibernate:
                dialect : org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
    instance:
      hostname: cloud-unified-service
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      preferIpAddress: true
    
    
    