server:
  port: 20015

spring:
  application:
    name: cloud-unified-service-core
  main:
    allow-bean-definition-overriding: true  
  datasource:
    url: jdbc:mysql://localhost:3306/saascloud?autoReconnect=true&characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    show-sql: true              
    properties:
            hibernate:
                dialect : org.hibernate.dialect.MySQL5Dialect

application:
  uploadDir: upload2
  uploadRootDir: D:\\temp\\files_dir


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20000/eureka
  instance:
      hostname: cloud-unified-service
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      preferIpAddress: true
    
    
    