
spring:
  application:
    name: cloud-shop
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/saascloud?autoReconnect=true&amp;characterEncoding=UTF-8&amp;useUnicode=true
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jpa:
    database: MYSQL
    show-sql: true
    
  main:
    banner-mode: 'off'
  mvc:
    date-format: yyyy-MM-dd
    favicon:
      enabled: false
  redis:
    database: 3
    host: 219.138.150.224
    password: 
    pool:
      max-active: 8  
      max-idle: 8  
      max-wait: -1  
      min-idle: 0  
    port: 10015 
    timeout: 0  
    
  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

logging:
  level:
    com:
      fp:
        gan:
          sms: DEBUG
    org:
      apache:
        catalina:
          session:
            ManagerBase: warn
      hibernate: ERROR
      springframework: WARN
      thymeleaf: ERROR
    root: DEBUG
    
server:
  context-path: /shop
  error:
    whitelabel:
      enabled: false
  port: 10002
  session:
    timeout: 3600
      
sso:
  appID: shop
  server:
    url: http://127.0.0.1:10000
  type: client
