
spring:
  application:
    name: cloud-shop
  #datasource:
  #  driverClassName: com.mysql.jdbc.Driver
  #  password: 123456
  #  url: jdbc:mysql://localhost:3306/saascloud?autoReconnect=true&amp;characterEncoding=UTF-8&amp;useUnicode=true
  #  username: root-not-ness
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  #jpa:
  #  database: MYSQL
  #  show-sql: true
    
  main:
    banner-mode: 'off'
  mvc:
    date-format: yyyy-MM-dd
    favicon:
      enabled: false
  redis:
    database: 3
    host: 219.138.150.224
    password: 
    port: 10015 
    timeout: 0      jedis:      pool:        min-idle: 0        max-wait: -1        max-idle: 8
    
  thymeleaf:
    cache: false
    check-template-location: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html    servlet:      content-type: text/html
    
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
  instance:
      hostname: cloud-shop
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      preferIpAddress: true

logging:
  level:
    com:
      org:
        cloud:
          shop: DEBUG
    org:
      apache:
        catalina:
          session:
            ManagerBase: warn
      hibernate: ERROR
      springframework: WARN
      thymeleaf: ERROR
    root: DEBUG
    
server:
  servlet:    context-path: /shop
    session:      timeout: 3600
  error:
    whitelabel:
      enabled: false
  port: 20014

      
sso:
  appID: shop
  server:
    url: http://127.0.0.1:20010
  type: client
