server:
  port: 9005

spring:
  application:
    name: cloud-mc-one
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&amp;characterEncoding=UTF-8&amp;useUnicode=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
            ddl-auto: create-drop 
            naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
              
    properties:
            hibernate:
                dialect : org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

    
    
    