
server:
  port: 8888


management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
 
eureka:
  instance:
    hostname: cloud-config
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: file:d:/temp/config-repo
       
