 eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

---
server:
  port: 20002
  #contextPath: /
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: cloud-authserver

  thymeleaf:
    check-template-location:  true
    prefix:  classpath:/templates/
    suffix:  .html
    mode:  HTML5
    encoding:  UTF-8
    content-type:  text/html
    cache:  false
  
  datasource:
    url: jdbc:mysql://localhost:3306/saascloud?autoReconnect=true&amp;characterEncoding=UTF-8&amp;useUnicode=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
            naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
              
    properties:
            hibernate:
                dialect : org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.springframework.security: WARN
