 eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /uaa/info
    healthCheckUrlPath: /uaa/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

--- 
server:
  contextPath: /uaa
  error:
    whitelabel:
      enabled: false


      
spring:
  application:
    name: cloud-authserver

  thymeleaf:
    check-template-location:  true
    prefix:  classpath:/templates/
    suffix:  .html
    mode:  HTML5
    encoding:  UTF-8
    content-type:  text/html
    cache:  false
  
      
security:
  user:
    password: password
  ignored:  /css/**,/js/**,/favicon.ico,/webjars/**,/

logging:
  level:
    org.springframework.security: DEBUG

  