debug: true

server:
  contextPath: /uaa
  error:
    whitelabel:
      enabled: false

# spring:
#  thymeleaf:
#    check-template-location:  true
#    prefix:  classpath:/templates/
#    suffix:  .html
#    mode:  HTML5
#    encoding:  UTF-8
#    content-type:  text/html
#    cache:  false
  
      
security:
  user:
    password: password
  ignored:  /css/**,/js/**,/favicon.ico,/webjars/**,/

logging:
  level:
    org.springframework.security: DEBUG
